image: hashicorp/terraform:1.12.2

variables:
  TF_VAR_token: $YC_TOKEN
  TF_VAR_cloud_id: $YC_CLOUD_ID
  TF_VAR_folder_id: $YC_FOLDER_ID
  TF_VAR_default_zone: $YC_DEFAULT_ZONE
  S3_ENDPOINT: "s3.storage.yandexcloud.net"
  S3_BUCKET: "my-homework-bucket-develop"
  AWS_ACCESS_KEY_ID: $S3_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: $S3_SECRET_KEY

stages:
  - init
  - plan
  - apply
  - destroy

terraform_init:
  stage: init
  tags:
    - terraform
  script:
    - terraform init \
        -backend-config="endpoint=${S3_ENDPOINT}" \
        -backend-config="access_key=${AWS_ACCESS_KEY_ID}" \
        -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}" \
        -backend-config="bucket=${S3_BUCKET}" \
        -backend-config="region=ru-central1" \
        -backend-config="use_path_style=true"
  artifacts:
    paths:
      - .terraform/
      - .terraform.lock.hcl
      - terraform.tfstate
      - terraform.tfstate.backup

terraform_plan:
  stage: plan
  tags:
    - terraform
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  dependencies:
    - terraform_init

terraform_apply:
  stage: apply
  tags:
    - terraform
  script:
    - terraform apply -auto-approve tfplan
  when: manual
  dependencies:
    - terraform_init
    - terraform_plan

terraform_destroy:
  stage: destroy
  tags:
    - terraform
  script:
    - terraform destroy -auto-approve
  when: manual
